### ISSUE TITLE
Release TODOs

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18868]
- [ ] sever-chart build and versioning change #17663
- [ ] Update cli to non-rc release in pipeline-tools image when it is available #17732

Release note known issues:
- [ ] Release note how the "backup/restore" feature works on existing clusters. #18754
- [ ] Manual backup snapshots should not get deleted on account on retention count and recurring snapshot creation time should not get altered based on manual backup taken. #18807
- [ ] When snapshot is disabled , We are not allowed to Restore from existing backups / take manual back ups. #18793

**Comment by alena1108** [comment]
- [ ] release RKE and update rancher to non-RC rke release

**Comment by loganhz** [comment]
Release windows images 😃

**Comment by cjellick** [comment]
release note: For GKE in 2.2 we have “enable Access Management (IAM) API”

**Comment by cjellick** [comment]
release note extra step needed for air gap because of system-library catalog
