### ISSUE TITLE
Windows 1809 Support Alpha

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19173]
#### OS
- [x] **Support Windows 1809**

#### Bugs
- [x]  **`nginx-proxy` container sometimes fails to start**: https://github.com/rancher/rancher/issues/16074
- [x] **kubelet (Kubernetes 1.12.) wont start on windows**: https://github.com/rancher/rancher/issues/17341
- [x] **Node scheduling problem Linux/Windows for Rancher System components**: https://github.com/rancher/rancher/issues/17423
- [x] **Support upgrade**: https://github.com/rancher/rancher/issues/19048
- [x] **Windows Nodes crashing after 2-3 days**: https://github.com/rancher/rancher/issues/17499

#### Enhancement
- [x] **Support Flannel VxLan mode**

**Comment by fedeostrit** [comment]
hi, a query all these improvements and fixes for windows host when they are going to be in version v2.2 or should we wait for version v2.3?
I do not understand when improvements for host windows merge and when they take it out of experimental states?
Sorry for the questions but I'm very new to Rancher and Kubernetes

**Comment by loganhz** [comment]
They are going to be in v2.2 I think.

**Comment by fedeostrit** [comment]
thanks for your quick response, I bother you with one more problem that I have in my cluster with 2 nodes with centos 7 and a node with windows 1803, the 3 hosts are in the same network 10.73.2.0/24 and there are also other VMs that are in that same network that has other services such as Oracle DB instances

The problem I have is that when I raise a caontainer in the Windows node, the container can not see the network 10.73.2.0/24, only see the 3 hosts that are in the cluster, if I raise a container in the Centos nodes if they can see the network 10.73.2.0/24 and you can also see other networks of my infrastructure

this is the CNI.config of the windows node:

{"capabilities":{"dns":true},"delegate":{"dns":{"search":["svc.cluster.local"],"nameservers":["10.43.0.10"]},"policies":[{"value":{"ExceptionList":["10.42.0.0/16","10.43.0.0/16","10.73.2.0/24"],"Type":"OutBoundNAT"},"name":"EndpointPolicy"},{"value":{"DestinationPrefix":"10.43.0.0/16","NeedEncap":true,"Type":"ROUTE"},"name":"EndpointPolicy"},{"value":{"DestinationPrefix":"10.73.2.224/32","NeedEncap":true,"Type":"ROUTE"},"name":"EndpointPolicy"}],"type":"win-bridge"},"name":"cbr0","type":"flannel","cniVersion":"0.2.0"}

the containers in the hosts with centos can see all the networks, I think it has to be something in that config but I can not change it because if I do it and restart the host it goes back to the configuration previous to the change

**Comment by waterfoul** [comment]
Are there published versions of these containers we can try?

**Comment by sangeethah** [comment]
All issues tracked in this bug have been validated on master builds.
