### ISSUE TITLE
[UI] - Istio - Integration GA

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19582]
* [x] Create a sample catalog app with deployments and istio config. https://github.com/rancher/rancher/issues/20897
* [x] Use IFrame to move the Kiali Graph into Rancher UI https://github.com/rancher/rancher/issues/20896
* [x] Support Istio Virtual Service and Destination Rule as first class resources in Rancher UI just like Workloads.  https://github.com/rancher/rancher/issues/20894
* [x] Cluster owner should be able to choose which users can see Kiali, Jaeger, Grafana and Prometheus UI.  https://github.com/rancher/rancher/issues/20895

NOTES:

Istio Integration alpha issue https://github.com/rancher/rancher/issues/19087

**Comment by davidnuzik** [comment]
@bmdepesa when you are done with @20894 could you close this epic issue?

I have already validated the 1st, 2nd, and 4th checkmarks. (for first just deploy and ensure works as expected).
