### ISSUE TITLE
v2.3 release notes

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22517]
This issue is the placeholder for what we need to capture in v2.3 release notes.

- [X] New API endpoints and potential deprecation of older k8s versions https://github.com/rancher/rancher/issues/22426#issuecomment-525510371
- [X] Windows Limitation: https://github.com/rancher/rancher/issues/20968, https://github.com/rancher/rancher/issues/20510#issuecomment-528013933
- [X ] Added tolerations to the the k8s versions, all system components will restart upon an edit of the cluster. 
- [X] Google Auth - your Rancher setup requires having an FQDN due to google's requirements
-  [x] Rancher CLI Change - `rancher app install` used to block until app was finished installing, but there were issues if you hit the 2 min timeout where it would error out, but the app might actually still deploy correctly. scripts need to be updated to use `rancher wait app install` in order to have the CLI return after the app has been deployed https://github.com/rancher/rancher/issues/17471 

- [x ] Istio - Istio will not work with the restricted PSP https://github.com/rancher/rancher/issues/22469
- [x] HPA - HPA UI doesn't work in GKE as GKE doesn't support `v2beta2.autoscaling` API https://github.com/rancher/rancher/issues/22292
- [x ] Taints available in node template on an upgraded setup from 2.2.8 to master-head can cause scheduling issues https://github.com/rancher/rancher/issues/22672 
- [x] Cluster creation "edit as yaml" changed - https://github.com/rancher/docs/issues/1736
- [x] Hardening guide Issues - Monitoring doesnt work https://github.com/rancher/rancher/issues/20884
kubectl in UI doesn't work https://github.com/rancher/rancher/issues/19439
Piprlines don't work = https://github.com/rancher/rancher/issues/22844
