### ISSUE TITLE
Rancherd GA

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29797]
Requirements:
- [x] Fix panic on startup when resset password #29565 
- [x] Pull in latest RKE2 (slated for 11/11 release) as this will contain etcd improvements #29825 
- [x] Config.yaml support #29422 
- [ ] Documentation (Airgap and upgrades) (needs rancher/docs issue)

QA Requirements: 
- [x] Initial automation (Jenkins) - Shylaja
- [x] Validate RHEL8 with SELinux set to Enforcing - Shylaja
- [x] Validate RHEL8 with SELinux set to Enforcing with cis-1.5 enabled (can automation have this on by default?) #30011 
- [x] Validate Airgap configuration. Take notes so this can get documented (sync notes with Catherine) #30012 
- [x] Validate rancherd upgrades (drop in newer binary or tarball and run, ensure upgrade success) #30013

**Comment by maggieliu** [comment]
@davidnuzik Please provide the QA requirements.

**Comment by davidnuzik** [comment]
@sowmyav27 @maggieliu apologies I missed this ping. I've updated the original issue description above. You can reach out to me if you have any questions.

**Comment by sangeethah** [comment]
Doc related changes are being tracked in https://github.com/rancher/docs/issues/2935
