### ISSUE TITLE
Create RKE2 clusters from Rancher

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30679]
EPIC for RKE2 provisioning from Rancher

**Expected result:**
It should be possible to provision nodes for and create RKE2 clusters from Rancher.

**Other details that may be helpful:**
Depending on the details of the design, it should not be difficult to also provision nodes for and create k3s clusters from Rancher with the same implementation.

Todo: 
- [ ] rancher-machine https://github.com/rancher/rancher/issues/30597 (To Test)
- [ ] ACE https://github.com/rancher/rancher/issues/31604 (To Test)
- [ ] RKE2 Config https://github.com/rancher/rancher/issues/32174
- [ ] Remove rancher-operator from feature charts https://github.com/rancher/rancher/issues/32179 (To Test)
- [ ] Add support to pass files during machine provisioning https://github.com/rancher/rancher/issues/32231
- [ ] Air-gap support https://github.com/rancher/rancher/issues/32403

**Comment by cbron** [comment]
I'm going to close this parent issue as it will be tracked in a different way.
