### ISSUE TITLE
EPIC: GKE Provisioner 

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31043]
Tracking our work tied to the gke-operator

- [x] Operator work: https://github.com/rancher/rancher/issues/31042
- [x] Cloud Creds: https://github.com/rancher/rancher/issues/30981 
- [x] Sync: https://github.com/rancher/rancher/issues/31010
- [x] Handler: https://github.com/rancher/rancher/issues/31011
- [x] Generic Refresher https://github.com/rancher/rancher/issues/31789
- [x] Set number of pods per node: https://github.com/rancher/rancher/issues/31110
- [x] Service account not being updated: https://github.com/rancher/rancher/issues/28527
- [x] Add to resourceset for backupoperator: https://github.com/rancher/rancher/issues/31281
- [x] Update Proxy calls: https://github.com/rancher/rancher/issues/31678
- [x] Add shared VPC calls any other new calls for GKEv2 https://github.com/rancher/rancher/issues/30864
- [x] Private GKE cluster https://github.com/rancher/rancher/issues/31895
- [ ] Update terraform: https://github.com/rancher/rancher/issues/31295
- [x] Drone pipeline multi-arch https://github.com/rancher/rancher/issues/31869
- [x] UI: https://github.com/rancher/rancher/issues/31221
- [x] Register cluster: https://github.com/rancher/rancher/issues/31461
- [ ] Docs: https://github.com/rancher/docs/issues/3105
- [ ] EKS Docs update: https://github.com/rancher/docs/issues/3133
~- [ ] Autopilot: https://github.com/rancher/rancher/issues/31918~
- [x] Cluster provisioning bug: https://github.com/rancher/rancher/issues/32032

Moved to 2.6, this epic can be closed before they are resolved.
- [ ] CSI driver: https://github.com/rancher/rancher/issues/32055
