### ISSUE TITLE
EPIC: AKS Provisioner

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31045]
Tracking our work for the aks-operator for Rancher.

- [x] Follow up from PR1: https://github.com/rancher/rancher/issues/31648
- [x] Cloud Creds: https://github.com/rancher/rancher/issues/31014
- [x] Sync: https://github.com/rancher/rancher/issues/31015
- [x] Handler: https://github.com/rancher/rancher/issues/31016
- [x] Update Proxy calls: https://github.com/rancher/rancher/issues/32399
- [x] Add new Proxy calls: https://github.com/rancher/rancher/issues/32587
- [x] Register cluster: https://github.com/rancher/rancher/issues/31462
- [x] Private cluster and private link: https://github.com/rancher/rancher/issues/25273
- [x] Windows compatibility: https://github.com/rancher/rancher/issues/32586
- [x] HTTP application routing: https://github.com/rancher/rancher/issues/32674
- [x] Provide the resource groups to the UI: https://github.com/rancher/rancher/issues/32699
- [x] Monitoring Azure Kubernetes Service: https://github.com/rancher/rancher/issues/32675
- [x] Node pool autoscaling: https://github.com/rancher/rancher/issues/32956
- [x] Make tenant optional: https://github.com/rancher/rancher/issues/32897
- [x] Complex nodepools bug: https://github.com/rancher/rancher/issues/32960
- [x] Update kev1 regions https://github.com/rancher/rancher/issues/32967
- [x] Request to notify if RBAC disabled: https://github.com/rancher/rancher/issues/27670
- [x] Request to notify if RBAC disabled - UI  https://github.com/rancher/rancher/issues/33307
- [x] Fix Azure network policy: https://github.com/rancher/rancher/issues/33202
- [x] Monitoring set to null: https://github.com/rancher/rancher/issues/33237
- [x] logAnalyticsWorkspaceName shows wrong value https://github.com/rancher/rancher/issues/33238
- [ ] updating k8s version of 'NP with autoscaling' from Azure, causes error https://github.com/rancher/rancher/issues/33446 

External issues
- [x] Add to resourceset for backupoperator: https://github.com/rancher/backup-restore-operator/issues/81
- [ ] Update terraform: https://github.com/rancher/rancher/issues/31296
- [x] UI: https://github.com/rancher/rancher/issues/31315
- [ ] Docs: https://github.com/rancher/docs/issues/3104
- [x] UI Monitoring: https://github.com/rancher/rancher/issues/33142

**Comment by cbron** [comment]
Throwing this one to test now. We only have one issue here not ready.
