### ISSUE TITLE
Validate Rancher supports k8s 1.22

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34060]
Due to the dropped APIs, there are significantly more checks needed to validate that k8s 1.22 can be supported. 

**Supporting installing Rancher onto k8s 1.22 clusters**
- [x] Validating runtime resources - https://github.com/rancher/rancher/issues/33222 
- [x] Updating Helm Server chart - https://github.com/rancher/rancher/issues/34058 
- [x] Ingress support - https://github.com/rancher/rancher/issues/33312 and https://github.com/rancher/rancher/issues/30053
[assigned] Dropping Component Status Support - https://github.com/rancher/rancher/issues/34055

**Supporting Downstream k8s 1.22 clusters**
[assigned] Supporting k8s 1.22 into Rancher to support 1.22 downstream clusters (client-go for 1.22) - https://github.com/rancher/rancher/issues/34054
- [x] Adding k8s 1.22 into KDM/RKE - https://github.com/rancher/rancher/issues/33114
[assigned] Adding k8s 1.22 for RKE2/k3s - https://github.com/rancher/rancher/issues/34056
- [x] Validating k8s 1.22 works for EKS - https://github.com/rancher/rancher/issues/33623
- [x] Validating k8s 1.22 works for AKS - https://github.com/rancher/rancher/issues/33622
- [x] Validating k8s 1.22 works for GKE - https://github.com/rancher/rancher/issues/33621

**Supporting Applications in k8s 1.22**
- [x] Continuous Delivery/Fleet - https://github.com/rancher/rancher/issues/33112
- [ ] Apps and Marketplace Apps - https://github.com/rancher/rancher/issues/34057
- [x] Legacy Apps - https://github.com/rancher/rancher/issues/34059

**Comment by HoseinGhanbari** [comment]
unfortunately there is no warning in the official docs noticing people like me that you cannot use the latest version of k3s which is now `v1.22.3+k3s1` to run the latest version of rancher until we, ourselves, reach to this ...
```
[FATAL] the server could not find the requested resource
```

**Comment by nilathedragon** [comment]
Just ran into this when upgrading my RKE2 Cluster... It's a bit inconvenient to have latest stable RKE2 not work with latest stable Rancher.

**Comment by davidgibbons** [comment]
Just to echo the above statements, would have loved a more obvious warning about compatibility before I wasted my night trying to deploy this on the latest stable RKE2

**Comment by kinarashah** [comment]
Rancher's support matrix shows which k8s versions are supported for k3s/rke2 - https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-2/ 

I do agree we can work on making this more obvious.

**Comment by modzilla99** [comment]
> Just to echo the above statements, would have loved a more obvious warning about compatibility before I wasted my night trying to deploy this on the latest stable RKE2

Yes I feel the same way, it really isn't obvious at all, it should be clearly stated in their deployment docs. This whole thing is a mess and support is getting pushed back realease by release. There isn't even a clear roadmap. At least as far as I can tell.

But if you're willing to run an RC the 2.6.3 version can be deployed on 1.22. clusters.
```
git clone --depth=1 -b v2.6.3-rc4 https://github.com/rancher/rancher
sed -i "s/%VERSION%/2.6.3-rc4/g" rancher/chart/Chart.yaml
sed -i "s/%APPVERSION%/2.6.3-rc4/g" rancher/chart/Chart.yaml
sed -i "s/%POST_DELETE_IMAGE_NAME%/rancher\/shell/g" rancher/chart/values.yaml
sed -i "s/%POST_DELETE_IMAGE_TAG%/v0.1.10/g" rancher/chart/values.yaml

helm install --create-namespace -n cattle-system rancher/chart/ rancher [-f values.yaml]
```

**Comment by corend** [comment]
Hi,

I see that @sowmyav27 you postponed to v2.6.4 instead of v2.6.3, unfortunately this bug is critical for us as our cluster is down due to this deployment issue: https://github.com/rancher/rancher/issues/35174 
Rancher is not installed correctly and the dependencies are also down due to this impact such as Longhorn volumes are down.
The cluster is just unusable at all and it cost money. Could you please push a bit to have this issue fix in the next version?
In my view, as this is critical it should be done via hotfixes, but if not possible then it should be included in the next version.

Thank you a lot and anyway we love your work ;)

**Comment by sowmyav27** [comment]
@corend We _are_ introducing k8s 1.22 as **experimental** in 2.6.3 Rancher release and will be GA in 2.6.4 Rancher release.

**Comment by slickwarren** [comment]
closing this ticket, as the only remaining issues are tracked for apps & marketplace:
Apps and Marketplace Apps - https://github.com/rancher/rancher/issues/34057
