### ISSUE TITLE
Rancher server with self signed certs

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3425]
@ibuildthecloud, creating this to keep track of the PRs.

The first pass at running Rancher with self signed certs

*  [x] rancher/python-agent#216
*  [x] rancher/rancher#3330
*  [x] rancher/cattle#1288
*  [x] rancher/cattle#1295
*  [x] rancher/cattle#1290
*  [x] rancher/agent-instance#13
*  [ ] rancher/rancher.github.io#182

There will need to be a follow on PR to Cattle to update the agent-instance base image and the rancher/agent image.

/cc @alena1108 @will-chan
