### ISSUE TITLE
Move user controllers to agent where possible

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#35540]
We want as many controllers as possible to run in the downstream cluster and not centrally.  This minimizes the amount of traffic flowing to the central Rancher.

- [x] endpoint - rancher/rancher#35539
- [x] ingresshostgen - rancher/rancher#35541
- [ ] nodesyncer - rancher/rancher#35556
- [x] nsserviceaccount - rancher/rancher#35557

**Comment by git-ival** [comment]
@ibuildthecloud Not able to determine a change in the available handlers from the listed PRs, the same set of related handlers seem to be available on both 2.6.2 and 2.6.3.

**Comment by git-ival** [comment]
Closing with the following:
* endpoint: did not find the error log message which was removed with this change (as expected), Additionally, UI links remain functional both on local, and downstream clusters
* ingresshostgen: this controller was not found on the local cluster (as expected)
* nodesyncer: still able to set limits and requests on node resources (as expected)
* nsserviceaccount: was able to verify the "sync" and "error" log messages appeared as expected, was not able to verify that the "Registering" debug log message was output.

Additionally, these changes have been in-place for various regular regression and scale-testing efforts without impacting the test results.
