### ISSUE TITLE
Tracking k8s v1.25 warnings 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#35558]
cluster-agent logs

- [ ] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
- [ ] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
- [ ] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+
