### ISSUE TITLE
[Group] RKE2 Provisioning parity work for RKE2 Provisioning GA

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#36044]
This ticket is to track RKE2 Provisioning validation

**RKE2**
 - [x] etcd snapshot/restore redesign to support cluster config - https://github.com/k3s-io/k3s/issues/4380 
 - [x] On-demand certificate rotation- https://github.com/k3s-io/k3s/issues/2636
 - [x] Rancher-managed encryption keys (with rotation)- https://github.com/rancher/rke2/issues/748 

**Rancher**
- [x] etcd snapshot support (with options) - https://github.com/rancher/rancher/issues/34417 
- [x] On-demand certificate rotation- https://github.com/rancher/rancher/issues/35343
- [x] ~~Rancher-managed encryption keys (with rotation)-  https://github.com/rancher/rancher/issues/35436~~ (removed from initial GA scope)
- [x] SSH to RKE2 nodes from Rancher CLI- https://github.com/rancher/rancher/issues/35203
- [x] Drain nodes on scale down- https://github.com/rancher/rancher/issues/35274
- [x] Self-healing node pools- https://github.com/rancher/rancher/issues/35275
- [x] vSphere version pinning- https://github.com/rancher/rancher/issues/35474
- [x] Terraform provider updates- https://github.com/rancher/terraform-provider-rancher2/issues/799

**Windows**
- [x] Windows - CIS Scans - https://github.com/rancher/windows/issues/107
- [x] Windows - Istio - https://github.com/rancher/windows/issues/108
- [x] Windows - CNI - Calico - PNI Support - https://github.com/rancher/windows/issues/106
- [x] Windows - RKE2 upgrade - https://github.com/rancher/windows/issues/76
- [x] Windows - Logging / Alerting / Monitoring

**UI**
 - [x] Scale down individual node - https://github.com/rancher/dashboard/issues/4446
 - [x] Drain nodes on scale down - https://github.com/rancher/dashboard/issues/4448
 - [x] Self-healing node pools - https://github.com/rancher/dashboard/issues/4449
 - [x] etcd snapshot/restore redesign to support cluster config - https://github.com/rancher/dashboard/issues/4539
 - [x] On-demand certificate rotation - https://github.com/rancher/dashboard/issues/4485
 - [x] ~~Rancher-managed encryption keys (with rotation) - https://github.com/rancher/dashboard/issues/4540~~ (removed from initial GA scope)
 - [x] S3 config support for UI - https://github.com/rancher/dashboard/issues/4551
 - [x] IPv6 dual-stack (front-end addition) - https://github.com/rancher/dashboard/issues/4550

**Comment by cwayne18** [comment]
@Sahota1225 I've marked off the 3 RKE2 issues as done (as they're all landed as of Dec release)

**Comment by snasovich** [comment]
Closing the issue since all individual issues are completed.

**Comment by braunsonm** [comment]
This being closed surprises me since you cannot restore RKE2 snapshots into a new cluster since they are encrypted now and there is no way to provide the token.

https://github.com/rancher/rancher/issues/36298

**Comment by snasovich** [comment]
@braunsonm , thank you for highlighting the issue you've linked, we will triage it with the team. Added a few labels and set the milestone on it to 2.6.6 for visibility purposes only (not a commitment to deliver it in 2.6.6).

As for closing this issue, it is specifically to track progress on issues identified as the initial scope of RKE2 Provisioning GA, and since all subtasks are now resolved this issue got closed.
