### ISSUE TITLE
v2.6.5 - Release Master Checklist

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37315]
### v2.6.5 - Release Checklist Master
Please use this for the tracking of the issues associated with the v2.6.5 release. Each section is broken up by team to help ensure proper tracking of the release.

### Team 2 Tasks

- [x] rancher/rancher/issues/37316
- [x] rancher/rancher/issues/37317
- [x] rancher/rancher/issues/37320

### Team 3 Tasks

- [x] rancher/rancher/issues/37323
- [x] rancher/rancher/issues/37326
- [x] rancher/rancher/issues/37329

## Release Captain Tasks

- [x] rancher/rancher/issues/37330
- [x] rancher/rancher/issues/37331
- [x] rancher/rancher/issues/37332
- [x] rancher/rancher/issues/37333
- [x] rancher/rancher/issues/37334
- [x] rancher/rancher/issues/37335 (& Team 3)
- [x] rancher/rancher/issues/37336 (& Team 3)
- [x] rancher/rancher/issues/37337 (& Team 2)
- [x] rancher/rancher/issues/37338
- [x] rancher/rancher/issues/37339
- [x] rancher/rancher/issues/37340
- [x] rancher/rancher/issues/37341
- [x] rancher/rancher/issues/37342
- [x] rancher/rancher/issues/37343
- [x] rancher/rancher/issues/37344

## Rancher Docs Tasks

- [x] rancher/docs/issues/4024
- [x] rancher/docs/issues/4025
- [x] rancher/docs/issues/4026
- [x] rancher/docs/issues/4027

## Rancher QA Tasks

- [x] rancher/rancher/issues/37346
- [x] rancher/rancher/issues/37347
- [x] rancher/rancher/issues/37348
- [x] rancher/rancher/issues/36327
- [x] https://github.com/rancher/qa-tasks/issues/208
- [x] https://github.com/rancher/qa-tasks/issues/221
- [x] https://github.com/rancher/qa-tasks/issues/222
- [x] https://github.com/rancher/qa-tasks/issues/223
- [x] https://github.com/rancher/qa-tasks/issues/224
- [x] https://github.com/rancher/qa-tasks/issues/225
- [x] https://github.com/rancher/qa-tasks/issues/228
- [x] https://github.com/rancher/qa-tasks/issues/229
- [x] https://github.com/rancher/qa-tasks/issues/230
- [x] https://github.com/rancher/qa-tasks/issues/231
- [x] https://github.com/rancher/qa-tasks/issues/232
- [x] https://github.com/rancher/qa-tasks/issues/248

## Rancher UI Tasks
- [x] rancher/dashboard/issues/5638
