### ISSUE TITLE
[Feature] K8s 1.26 support

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#41113]
Implement k8s 1.26 support. 

As a part of k8s upgrade usually we bump k8s libraries. But while bumping k8s libraries to 1.26.x , It is required to bump cluster-api to 1.4.x due to a breaking change in **k8s.io/apimachinery**.
keeping cluster-api at 1.2.x and bumping other kubernetes libraries results in following error
```
# sigs.k8s.io/cluster-api/api/v1beta1
vendor/sigs.k8s.io/cluster-api/api/v1beta1/machineset_types.go:184:83: not enough arguments in call to metav1validation.ValidateLabelSelector
        have (*"k8s.io/apimachinery/pkg/apis/meta/v1".LabelSelector, *field.Path)
        want (*"k8s.io/apimachinery/pkg/apis/meta/v1".LabelSelector, "k8s.io/apimachinery/pkg/apis/meta/v1/validation".LabelSelectorValidationOptions, *field.Path)
```
The plan moving forward is to remove cluster-api dependency completely from rancher repository. ref: https://github.com/rancher/rancher/issues/41094

So for kubernetes 1.26 support it is decided that the k8s libraries will be kept at 1.25.x version only.

## TODOs in Each Repo 
- [X] rancher/hyperkube
 	- hyperkube image for 1.26.4: https://github.com/rancher/hyperkube/pull/313
 
- [X] rancher/kubernetes
 	- create a tag for 1.26.4: https://github.com/rancher/kubernetes/pull/83
 	
- [X] rancher/kontainer-driver-metadata 
	- add 1.26.4 or newer:
		- update CNI images and templates ( canal, calico, flannel and weave)  
		https://github.com/rancher/kontainer-driver-metadata/pull/1133
		https://github.com/rancher/kontainer-driver-metadata/pull/1134
		- mirror or tag new images for each component:
		   https://github.com/rancher/image-mirror/pull/383
		   https://github.com/rancher/image-mirror/pull/384
		   https://github.com/rancher/image-mirror/pull/386
		   
- [X] rancher/flannel-cni 
    - bump cni plugin and flannel cni plugin version: https://github.com/rancher/flannel-cni/pull/10

- [X] rancher/rke-tools
    - update cri-dockerd to 0.3.1 	https://github.com/rancher/rke-tools/pull/162 
       	[other dependency bumps, not necessary for 1.26 testing] https://github.com/rancher/rke-tools/pull/161

- [X] rancher/rke
    - update latest KDM changes for 1.26
      https://github.com/rancher/rke/pull/3237
      https://github.com/rancher/rke/pull/3241
      
- [X] rancher/rancher
    - bump CAPI to 1.2.12, and check if CAPI crds needs to be updated.
    - update the embedded k3s cluster to 1.26.4 or newer
    - update max kuberntes version in chart.yaml
    https://github.com/rancher/rancher/pull/41285 (for all three)
    
- [X] rancher/lasso
    - update controller-runtime library to v0.12.3 to keep it in sync with CAPI. https://github.com/rancher/lasso/pull/40
    
- [X] add RKE2/K3s 1.26 
	- see details at https://github.com/rancher/rancher/issues/41376
	https://github.com/rancher/kontainer-driver-metadata/pull/1135
	
- [x] update charts to support 1.26
       - [ ] [aks-operator](https://github.com/rancher/aks-operator/issues/177)
       - [ ] [eks-operator](https://github.com/rancher/eks-operator/issues/137)
       - [ ] [gke-operator](https://github.com/rancher/gke-operator/issues/107)

SURE-5961
SURE-5962

**Comment by bastosvinicius** [comment]
Hello everyone, I installed Kubernetes version v1.26.3+rke2r1 and I'm trying to install Rancher, but I saw that it's not supported yet and I found this issue where you are working on these implementations.

How can I do the installations in my cluster and test these features that you are implementing?

**Comment by snasovich** [comment]
@bastosvinicius , thank you for your interest in this feature.
With every change merged we publish new `rancher/rancher` image with `v2.7-head` to DockerHub so it can be used to evaluating the most recent Rancher in-development image (with the obvious disclaimers associated with using in-development artifacts).

As we start tagging release candidate versions, corresponding Helm charts will be posted to rancher-latest Helm repo (https://releases.rancher.com/server-charts/latest), e.g. you can see RCs for 2.7.2 that we have recently released (again, the same disclaimers apply):
```
➜  ~ helm search repo rancher -l --devel
NAME                  	CHART VERSION   	APP VERSION      	DESCRIPTION
rancher-latest/rancher	2.7.2           	v2.7.2           	Install Rancher Server to manage Kubernetes clu...
rancher-latest/rancher	2.7.2-rc9       	v2.7.2-rc9       	Install Rancher Server to manage Kubernetes clu...
rancher-latest/rancher	2.7.2-rc8       	v2.7.2-rc8       	Install Rancher Server to manage Kubernetes clu...
rancher-latest/rancher	2.7.2-rc7       	v2.7.2-rc7       	Install Rancher Server to manage Kubernetes clu...
...
```

I don't have an ETA when k8s version constraint will be updated in Helm chart to include 1.26 yet.

**Comment by kinarashah** [comment]
Available to test with RKE `v1.4.3-rc6` and Rancher `v2.7-head`

**Comment by vivek-shilimkar** [comment]
### Summary of K8s v1.26 support testing checklist.
https://confluence.suse.com/display/RANQA/K8s+1.26+support

- :stopwatch:  =   Not started
- :clock12:  =   In progress
- :no_entry:  =   Blocked
- :heavy_check_mark:  =  PASSED
- :question: =  Have Question

- Local cluster checks - heavy_check_mark
  - Docker Install - :heavy_check_mark:
  - Docker install and Upgrade - :heavy_check_mark:
  - HA install -  :heavy_check_mark:

- RKE1 Validations
  - OS Certification -  :heavy_check_mark:
  - Hosted Clusters testing - :heavy_check_mark:

- KDM Testing -
  - Fresh Install Checks -  :heavy_check_mark:
  - Upgrade checks -  :heavy_check_mark:
  - Canal + PNI enabled - :heavy_check_mark:
  - Downstream cluster ETCD Validation - :heavy_check_mark:  PASS - on rancher v2.7-head(1f014b7)
  - Downstream Control Plane Validation - :heavy_check_mark:  PASS - on rancher v2.7-head(1f014b7)

- Feature charts testing - :clock12:  - https://github.com/rancher/rancher/issues/41395
- Local cluster RKE1 HA upgrade -   :heavy_check_mark:
- Local cluster RKE2 HA upgrade -   :heavy_check_mark:
- Local cluster K3s HA upgrade -   :heavy_check_mark:
- RKE checks - :heavy_check_mark:
- Rancher CLI checks - :heavy_check_mark:
- RKE2 and K3s Checks - 

  - Downstream RKE2 cluster provisioning - :heavy_check_mark:
    - Fresh install :heavy_check_mark:
    - Upgrade :heavy_check_mark:
  - Downstream k3s cluster provisioning - 
    - Fresh install :heavy_check_mark:
    - Upgrade  :no_entry: - https://github.com/rancher/rancher/issues/41582

- Windows RKE2 provisioning - :heavy_check_mark:
- RKE2 Amazon Cloud provider enabled checks. - :heavy_check_mark:
- Any other functional check for 1.26 - Service accounts -
- Airgap checks - :heavy_check_mark:
  - RKE1 cluster - custom clusters - :heavy_check_mark:
  - RKE2 clusters - custom clusters - :heavy_check_mark:
  - K3s clusters - custom clusters - :heavy_check_mark:

- Performance/scale testing -  :clock12:  (Brandon's team)  - https://github.com/rancher/qa-tasks/issues/711
- PSACT testing - :heavy_check_mark: (Markus)
- Conformance Checks - CNCF Conformance tests for RKE Kubernetes cluster
  - Rancher -  :heavy_check_mark: PR Raised
  - RKE - :heavy_check_mark:  PR Merged

**Comment by vivek-shilimkar** [comment]
All the checks finished and passed. Hence moving ticket to release task.
