### ISSUE TITLE
Update rancher/shell for Q2 milestone

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#41528]
This issue is for updating [rancher/shell](https://github.com/rancher/shell) to a non-rc version in Q2. It is also for keeping track of the changes made in Q2.

Steps:

- [ ] Make any required changes to [rancher/shell](https://github.com/rancher/shell), linking this issue in those PRs
- [ ] When ready for release, create a new [non-rc release](https://github.com/rancher/shell/tags) of [rancher/shell](https://github.com/rancher/shell)
- [ ] Update the version here: https://github.com/rancher/rancher/blob/c349805abca0ba09f5056daeae3bf49da87590ce/pkg/settings/setting.go#L121

**Comment by sowmyav27** [comment]
To Validate: 
> anytime you perform action in UI and you get that little box. When you press the “kubectl shell” button, and also if you deploy an app from marketplace.

**Comment by anupama2501** [comment]
Validations look good. Closing the issue.
