### ISSUE TITLE
[Feature] K8s 1.27 Support

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#41840]
Add support for K8s 1.27

## TODOs in Each Repo 

- [x] rancher/kubernetes
 	- Merge PR and create a tag for 1.27.5: https://github.com/rancher/kubernetes/pull/107

- [x] rancher/image-mirror
 	- etcd: https://github.com/rancher/image-mirror/pull/449
 	- calico & cilium: https://github.com/rancher/image-mirror/pull/411
 	- flannel: https://github.com/rancher/image-mirror/pull/454

- [x] rancher/hyperkube
 	- hyperkube image for 1.27.5 https://github.com/rancher/hyperkube/pull/326
 	
- [x] rancher/kontainer-driver-metadata 
	- add 1.27.5 or newer: https://github.com/rancher/kontainer-driver-metadata/pull/1204
		- update images and templates
		        - calico: https://github.com/rancher/kontainer-driver-metadata/pull/1206 and  https://github.com/rancher/calico-cni/pull/7
		        - canal: Same as calico
		        - ingress-nginx: https://github.com/rancher/ingress-nginx/pull/125 and https://github.com/rancher/kontainer-driver-metadata/pull/1205
		        - flannel: https://github.com/rancher/flannel-cni/pull/11 and https://github.com/rancher/kontainer-driver-metadata/pull/1211
		          

- [x] add RKE2/K3s `v1.27.5`: https://github.com/rancher/rancher/issues/42590

- [x] rancher/lasso
   - update k8s deps to 0.27.4, https://github.com/rancher/lasso/pull/51
   - update controller runtime to 0.15.0
   - bump go version to 1.20

- [x] rancher/rke
	- update latest KDM data for 1.27.4: https://github.com/rancher/rke/pull/3344
	- https://github.com/rancher/rancher/issues/42730

- [x] rancher/client-go
	- bump client-go to 0.27.4, https://github.com/rancher/client-go/pull/6

- [x] rancher/wrangler
	- bump k8s dependenciesto 0.27.4 and go version to 1.20. https://github.com/rancher/wrangler/pull/314

- [x] rancher/norman
	- bump k8s dependenciesto 0.27.4 and go version to 1.20. https://github.com/rancher/norman/pull/448

- [x] rancher/apiserver
	- bump k8s dependenciesto 0.27.4 and go version to 1.20. https://github.com/rancher/apiserver/pull/37

- [x] rancher/rancher: https://github.com/rancher/rancher/pull/42808

- update charts to support 1.27
  - [x] rancher/rancher#41796
  - [x] rancher/rancher#41797
  - [x] rancher/rancher#41798

SURE-6348

**Comment by vivek-shilimkar** [comment]
### Summary of K8s v1.27 support testing checklist.

- :stopwatch:  =   Not started
- :clock12:  =   In progress
- :no_entry:  =   Blocked
- :white_check_mark:  =  PASSED :white_check_mark: 
- :question: =  Have Question

- Local cluster checks - white_check_mark
  - Docker Install - :white_check_mark:
  - Docker install and Upgrade - :white_check_mark:
  - HA install -  :white_check_mark:

- RKE1 Validations
  - OS Certification -  :white_check_mark:
  - Hosted Clusters testing - :white_check_mark:

- KDM Testing -
  - Fresh Install Checks -  :white_check_mark:
  - Upgrade checks -  :white_check_mark:
  - Canal + PNI enabled - :white_check_mark:
  - Downstream cluster ETCD Validation - :white_check_mark:  PASS  
  - Downstream Control Plane Validation - :white_check_mark:  PASS 

- Feature charts testing - :clock12:  - https://github.com/rancher/rancher/issues/41720
- Local cluster RKE1 HA upgrade -   :white_check_mark:
- Local cluster RKE2 HA upgrade -   :white_check_mark:
- Local cluster K3s HA upgrade -   :white_check_mark:
- RKE checks - :white_check_mark:
- Rancher CLI checks - :white_check_mark:
- RKE2 and K3s Checks - 

  - Downstream RKE2 cluster provisioning - :white_check_mark:
    - Fresh install :white_check_mark:
    - Upgrade :white_check_mark:
  - Downstream k3s cluster provisioning - 
    - Fresh install :white_check_mark:
    - Upgrade  :white_check_mark: 

- Windows RKE2 provisioning :white_check_mark:
- RKE2 Amazon Cloud provider enabled checks. - :white_check_mark:
- Any other functional check for 1.26 - Service accounts - :white_check_mark: 
- Airgap checks - :white_check_mark:
  - RKE1 cluster - custom clusters - :white_check_mark:
  - RKE2 clusters - custom clusters - :white_check_mark:
  - K3s clusters - custom clusters - :white_check_mark:

- Performance/scale testing - :clock12:  (bullseye team)  - https://github.com/rancher/qa-tasks/issues/940
- PSACT testing - :white_check_mark: (Markus)
- Conformance Checks - CNCF Conformance tests for RKE Kubernetes cluster
  - Rancher -  :white_check_mark: PR Raised
  - RKE - :white_check_mark:  PR Merged

**Comment by mitulshah-suse** [comment]
Closing this issue since pending testing is being tracked in other issues which have been raised.
