### ISSUE TITLE
[Feature] k8s 1.29 support - apps and feature charts

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43690]
Parent issue: https://github.com/rancher/rancher/issues/43110

**Team Mapps**

- [x] #45457
- [x] https://github.com/rancher/rancher/issues/45458
- [x] https://github.com/rancher/rancher/issues/45459

**Team Framework**

- [x] https://github.com/rancher/rancher/issues/45351

**Team Socket**

- [x] https://github.com/rancher/rancher/issues/45461

**Team Hostbusters**

- [x] https://github.com/rancher/rancher/issues/45462
- [x] https://github.com/rancher/rancher/issues/45463
- [x] https://github.com/rancher/rancher/issues/45464

**Observability and Backup**

- [x] [prometheus-federator](https://github.com/rancher/rancher/issues/45352) k8s 1.29 chart support 
- [x] [rancher-logging k8s ](https://github.com/rancher/rancher/issues/45356)1.29 chart support  
- [x] [rancher-monitoring](https://github.com/rancher/rancher/issues/45354) k8s 1.29 chart support 
- [ ] [rancher-alerting-drivers](https://github.com/rancher/rancher/issues/45355) k8s 1.29 chart support
- [x] [rancher-backup ](https://github.com/rancher/rancher/issues/44097)k8s 1.29 chart support 
- [x] [rancher-charts ](https://github.com/rancher/rancher/issues/45620)k8s 1.29 chart support 

**Infracloud**
- [x] https://github.com/rancher/rancher/issues/45465 (Infracloud) 

**Fleet**

- [x] https://github.com/rancher/rancher/issues/45466

**Highlander**

- [x] https://github.com/rancher/rancher/issues/45467
- [x] https://github.com/rancher/rancher/issues/45468
- [x] https://github.com/rancher/rancher/issues/45469

**Harvester**

- [x] https://github.com/rancher/rancher/issues/45470
- [x] https://github.com/rancher/rancher/issues/45471

**Longhorn**

- [x] https://github.com/rancher/rancher/issues/45472

**NeuVector**

- [x] https://github.com/rancher/rancher/issues/45473

**Kubewarden**

- [x] https://github.com/rancher/rancher/issues/45474

**Comment by elektro-wolle** [comment]
Is there a timeline when 1.29 is expected to work with rancher? Or is it feasible to just remove the `< 1.28.0` constraint in the helm charts?

**Comment by gaktive** [comment]
For reference, the development work is going into a 2.8.x branch first through https://github.com/rancher/rancher/issues/43110. It will then be forward ported to 2.9 in https://github.com/rancher/rancher/issues/43965.

**Comment by snasovich** [comment]
@gaktive , this has changed a bit since last week so updating milestone to `v2.9-Next1` with the same rationale as https://github.com/rancher/rancher/issues/43110#issuecomment-2043546582. FYI @Sahota1225

**Comment by nicholasSUSE** [comment]
@gaktive @gunamata 
Please are these changes for dev-v2.8 or dev-v2.9?

**Comment by gaktive** [comment]
@nicholasSUSE 2.9.0 is the primary objective for now. At some point, we'll look at 2.8.x but that is secondary and likely after that release.

**Comment by Sahota1225** [comment]
- Since the charts have been released, can we close this issue? @nicholasSUSE
