### ISSUE TITLE
Complete branching steps for Rancher 2.9 for Harvestor

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43838]
**Tasks**

- [ ] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a  particular Rancher minor version, in this case it would be the Rancher 2.9 line.
- [ ] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. 
- [ ] testing

**Comment by bk201** [comment]
@w13915984028 please help check the cloud-provider chart,
@Vicente-Cheng please help check the csi chart. Thanks!

**Comment by Vicente-Cheng** [comment]
update harvester csi driver PR as below
PR: https://github.com/rancher/charts/pull/3301

- [ ] change the rancher-version annotation to catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0' while adding charts to dev-v2.9 branch. We do this so we can add patches to a particular Rancher minor version, in this case it would be the Rancher 2.9 line.
- [ ] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z.
- [ ] testing

**Comment by w13915984028** [comment]
Bump chart cloud-provider-harvester to v0.2.2
PR: https://github.com/rancher/charts/pull/3316

 - [x] change the rancher-version annotation to catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0' while adding charts to dev-v2.9 branch. We do this so we can add patches to a particular Rancher minor version, in this case it would be the Rancher 2.9 line.
- [x] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. (104.0.0+up0.2.2) 
- [ ] testing
