### ISSUE TITLE
Complete branching steps for Rancher 2.9 for EKS Operator

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43851]
**Tasks**

- [x] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a  particular Rancher minor version, in this case, it would be the Rancher 2.9 line.
- [x] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. 
- [ ] testing

**PR's**

- [x] https://github.com/rancher/charts/pull/3339

**Comment by cpinjani** [comment]
Validated as fixed on build: `v2.9-12467fadeb539d35a249702dc0933bd84a166433-head` using fresh install setup and upgraded setup from 2.8.1 > 2.9-head

EKS operator p0 scenarios are passed and version installed is	`rancher-eks-operator:104.0.0+up1.4.0-rc1`
