### ISSUE TITLE
[Backport 2.7.11]  1.27 Chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44126]
Parent issue: https://github.com/rancher/rancher/issues/44098

Backport of https://github.com/rancher/rancher/issues/41720

**Team Mapps**

- [x] https://github.com/rancher/rancher/issues/44103
- [x] https://github.com/rancher/rancher/issues/44104
- [x] https://github.com/rancher/rancher/issues/44106
- [x] https://github.com/rancher/rancher/issues/44105

**Team 2**

- [x] https://github.com/rancher/rancher/issues/44114
- [x] https://github.com/rancher/rancher/issues/44116
- [x] https://github.com/rancher/rancher/issues/44119

**Team 13**

- [x] https://github.com/rancher/rancher/issues/44066
- [x] https://github.com/rancher/rancher/issues/44100
- [x] https://github.com/rancher/rancher/issues/44099
- [x] https://github.com/rancher/rancher/issues/44096
- [x] https://github.com/rancher/rancher/issues/44102
- [x] https://github.com/rancher/rancher/issues/44101

**Socket**

- [x] https://github.com/rancher/rancher/issues/44107

**Fleet**

- [x] https://github.com/rancher/rancher/issues/44127

**Highlander**

- [x] https://github.com/rancher/rancher/issues/44109
- [x] https://github.com/rancher/rancher/issues/44111
- [x] https://github.com/rancher/rancher/issues/44113

**Harvester**

- [x] https://github.com/rancher/rancher/issues/44121
- [x] https://github.com/rancher/rancher/issues/44122

**Longhorn**

 - [x] https://github.com/rancher/rancher/issues/44123

**Epinio**

- [x] https://github.com/rancher/rancher/issues/44124

**NeuVector**

- [x] https://github.com/rancher/rancher/issues/44125

**Kubewarden**

- [x] https://github.com/kubewarden/kubewarden-controller/issues/613

**Other / Misc**

- [x] https://github.com/rancher/rancher/issues/44350

**Comment by recena** [comment]
@MKlimuszka The ownership definition can be found [here](https://github.com/rancher/charts/blob/dev-v2.7.11/.github/CODEOWNER).

**Comment by snasovich** [comment]
Closing as all charts were validated / released and v2.7.11 is already released.
