### ISSUE TITLE
[Feature] K8s 1.30 Support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45089]
Umbrella issue for supporting K8s 1.30 in Rancher.

See preliminary research done in spike https://github.com/rancher/rancher/issues/44210

For k8s 1.30, go version needs to updated to 1.22.x and [k8s.io/gengo](http://k8s.io/gengo)  library is upgraded to [k8s.io/gengo/v2](http://k8s.io/gengo/v2)  [ref](https://github.com/kubernetes/kubernetes/blob/02365ecec1cb1ddf993cf4ed12407737db950cea/CHANGELOG/CHANGELOG-1.30.md?plain=1#L672)

It has a few breaking changes.

- args package is removed from gengo/v2: [ref](https://github.com/kubernetes/gengo/commit/3446e13d19793807bcda5439c2baa0cc17893b6e)
- deepcopy-gen generators are moved to [k8s.io/code-generator](http://k8s.io/code-generator)  [ref](https://github.com/kubernetes/kubernetes/commit/cb7f0593aead2d9e5748d95e52e983e7eef93c62)

gengo is dependency in following repositories:
1. rancher/wrangler
  - [X] https://github.com/rancher/rancher/issues/45324 PRs for the issue are merged and new wrangler [tag](https://github.com/rancher/wrangler/tree/v3.0.0-rc2) is updated in rancher.
2. rancher/norman
 - [X] https://github.com/rancher/rancher/issues/45301  PRs for the issue are merged and norman is updated to latest in rancher.
3. rancher/rke
  - [X] PR https://github.com/rancher/rke/pull/3608 is merged and new [tag](https://github.com/rancher/rke/commits/v1.6.0-rc7) updated in rancher
4. rancher/rancher
 - [X] https://github.com/rancher/rancher/pull/45483 PR is merged.

other libraries which needs dependency upgrade:
 1. rancher/lasso
   - [X] https://github.com/rancher/rancher/issues/45216 [PR](https://github.com/rancher/lasso/pull/71) for the issue is merged and lasso is updated with those in rancher.
  2. rancher/helm
  - [X] PRs https://github.com/rancher/helm/pull/50 and https://github.com/rancher/helm/pull/51 are merged and helm is updated in rancher
  3. rancher/machine:
  - [X] PR: https://github.com/rancher/machine/pull/251 merged and new [tag](https://github.com/rancher/machine/tree/v0.15.0-rancher114) created and updated in rancher 
  4. rancher/channelsrever
  - needs wrangler updated from v2 to v3
  - [X]  PR: https://github.com/rancher/channelserver/pull/27 is merged and [tag](https://github.com/rancher/channelserver/tree/v0.7.0) is updated in rancher
  5. rancher/steve
  - [X]  https://github.com/rancher/rancher/issues/45332 PR for the issue is merged and steve is updated in rancher
  6. rancher/aks-operator
  - [X] latest [tag](https://github.com/rancher/aks-operator/tree/v1.9.0-rc.9) contains wrangler update and k8s dependencies update. The tag is updated in rancher. [PR](https://github.com/rancher/aks-operator/pull/538)
 7. rancher/eks-operator
  - [X] latest [tag](https://github.com/rancher/eks-operator/tree/v1.9.0-rc.9) contains wrangler update and k8s dependencies update. The tag is updated in rancher. [PR](https://github.com/rancher/eks-operator/pull/610)
 8. rancher/gke-operator
  - [X] latest [tag](https://github.com/rancher/gke-operator/tree/v1.9.0-rc.8) contains wrangler update and k8s dependencies update. The tag is updated in rancher. [PR](https://github.com/rancher/gke-operator/pull/517)
 9. rancher/shepherd
  - [X] [PR](https://github.com/rancher/shepherd/pull/219) is merged and shepherd is updated in rancher.
10. rancher/dynamiclistener:
  - [X] https://github.com/rancher/rancher/issues/45334 the PR for the issue is merged and the latest [tag](https://github.com/rancher/dynamiclistener/tree/v0.6.0-rc1) is updated in rancher. 
11. rancher/provisioning:
  - [X] updated images in image-mirror with https://github.com/rancher/image-mirror/pull/655
  - [X] CAPI is updated to v1.7.3 with [PR](https://github.com/rancher/provisioning/pull/11) and chart [PR](https://github.com/rancher/charts/pull/4107) is also merged. The latest chart version is also updated in rancher
 
  
  
  
  

Additional items:
- [ ] Update RKE1 Weave handling to fail on 1.30+ per https://github.com/rancher/rke/issues/3338 / https://github.com/rancher/rke/pull/3337/files#diff-f880d1cec512bd95e21c1cf1f15153fdfa89b256b84079de4757de7a4f951e17R753 
 issue: https://github.com/rancher/rancher/issues/45954

**Comment by tomleb** [comment]
Fwiw, [k8s.io/apiserver/pkg/apis/config](https://github.com/kubernetes/apiserver/tree/release-1.30/pkg/apis/config) no longer exists. It's used here:
- [github.com/rancher/rancher/pkg/controllers/management/secretmigrator/assemblers](https://github.com/rancher/rancher//blob/release/v2.9/pkg/controllers/management/secretmigrator/assemblers/assemblers.go#L14)
- [github.com/rancher/rancher/pkg/schemas/management.cattle.io/v3](https://github.com/rancher/rancher//blob/release/v2.9/pkg/schemas/management.cattle.io/v3/schema.go#L14)

**Comment by mallardduck** [comment]
A new shell RC [v0.2.1-rc.4](https://github.com/rancher/shell/releases/tag/v0.2.1-rc.4) has been cut ready for use with the updated helm version.

**Comment by snasovich** [comment]
For release notes, we would like to include the following limitations:
* https://github.com/rancher/rancher/issues/46132 (planned to be addressed in July RKE2 patches)
* For Azure cloud provider support (https://github.com/rancher/rancher/issues/44856 / https://github.com/rancher/rancher/issues/44857) we would like to add a note about UI changes not in 2.9.0 (https://github.com/rancher/dashboard/issues/11360) so "Edit as YAML" is a workaround.

**Comment by vivek-shilimkar** [comment]
### Summary of K8s v1.30 support testing checklist.

- :stopwatch:  =   Not started
- :clock12:  =   In progress
- :no_entry:  =   Blocked
- :white_check_mark:  =  PASSED :white_check_mark: 
- :question: =  Have Question

- Local cluster checks - :white_check_mark:
  - Docker Install - :white_check_mark:
  - Docker install and Upgrade - :white_check_mark:
  - HA install -  :white_check_mark:
  - Local Cluster HA Upgrade - :white_check_mark: 

- OS Certification -  :white_check_mark:
- Hosted Clusters testing - :white_check_mark:

- KDM Testing - :white_check_mark: 
  - Fresh Install Checks -  :white_check_mark:
  - Upgrade checks -  :white_check_mark:
  - Canal + PNI enabled - :white_check_mark:
  - Downstream cluster ETCD Validation - :white_check_mark:  PASS  
  - Downstream Control Plane Validation - :white_check_mark:  PASS 

- ETCD Validations - :white_check_mark: 
- Control plane Validations - :white_check_mark: 

- Local cluster HA updgrade
  - Local cluster RKE1 HA upgrade -   :white_check_mark:
  - Local cluster RKE2 HA upgrade -   :white_check_mark:
  - Local cluster K3s HA upgrade -   :white_check_mark:

- RKE checks - :white_check_mark:
- Rancher CLI checks - :white_check_mark:

- Windows RKE2 provisioning :white_check_mark:
- RKE2 Amazon Cloud provider enabled checks. - :white_check_mark: 
- Any other functional check for 1.27 - Service accounts - :white_check_mark:

- Airgap checks - :white_check_mark:
  - RKE1 cluster - custom clusters - :white_check_mark:
  - RKE2 clusters - custom clusters - :white_check_mark:
  - K3s clusters - custom clusters - :white_check_mark:

- Conformance Checks - CNCF Conformance tests for RKE Kubernetes cluster
  - Rancher -  :white_check_mark: PR Merged
  - RKE - :white_check_mark:  PR Merged

- RKE2 and K3s Checks - :white_check_mark: 
- 
- Node Driver Cluster Provisioning - :white_check_mark: 
  - Downstream RKE2 cluster provisioning - :white_check_mark:
    - Fresh install :white_check_mark:
    - Upgrade :white_check_mark:
  - Downstream k3s cluster provisioning - :white_check_mark: 
    - Fresh install :white_check_mark:
    - Upgrade  :white_check_mark:

**Comment by vivek-shilimkar** [comment]
Since OS checks are still remaining, moving tickets back to Actively QAing.
