### ISSUE TITLE
[EPIC] SQLite backed cache in the Steve API - iteration 1

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#45635]
Done in 2.9.0:

- [x] rancher-docs: explain new flags and experimental status, security warnings (ping @MbolotSuse ) https://github.com/rancher/rancher-docs/pull/1337 **◎**
- [x] properly merge https://github.com/rancher/rancher/pull/45679 **◎**
- [x] fix returned `count`: should be the total number of resources rather than the number of resources in the current page ([context](https://suse.slack.com/archives/C06TMDMJQ0M/p1718282561968269)) https://github.com/rancher/lasso/pull/84 + https://github.com/rancher/steve/pull/236  **◎**
- [x] Ensure cached backed API is available in downstream clusters without manually applying feature setting in downstream clusters ([context](https://suse.slack.com/archives/C06TMDMJQ0M/p1717611634290919)) https://github.com/rancher/rancher/pull/45787 **◎**
- [x] check that filter params ordering condition does not affect response (should be treated as OR, the current API has a bug) **◎**
- [x] If an invalid filter or sort is supplied API should respond with a 4XX status code and a helpful message mentioning which one's aren't invalid (In progress, solution imminent) **◎**
- [x] SQL injection prevention: make sure all table/column names are always sanitized (move sanitization code closer to SQL) (partial [context](https://github.com/rancher/lasso/pull/65#discussion_r1610555036), more [context](https://github.com/rancher/lasso/pull/65#discussion_r1611626853)) https://github.com/rancher/lasso/pull/85 ◎
- [x] add a test that will fail if the UnsafeHack breaks upon client-go updates ◎ https://github.com/rancher/lasso/pull/86
- [x] fix [issue 575](https://github.com/rancherlabs/embargoed-security/issues/575#issuecomment-2173474308) **S**
- [x] ask security to have another pass **S**

**Comment by moio** [comment]
Post 2.9.0 items moved off to https://github.com/rancher/rancher/issues/46348
