### ISSUE TITLE
[EPIC] SQLite backed cache in the Steve API - iteration 2

### ISSUE THREAD

**Issue by moio** [rancher/rancher#46348]
Blockers for turning on the feature by default in 2.10.0:

Bullseye Team to implement:

- [x] https://github.com/rancher/rancher/issues/46331
- [x] https://github.com/rancher/rancher/issues/46701

Frameworks Team to implement:
- [ ] ~https://github.com/rancher/rancher/issues/46332 (with Bullseye to help with design)~ closed in favor of  https://github.com/rancher/rancher/issues/40773
- [x] https://github.com/rancher/rancher/issues/46330 
- [x] https://github.com/rancher/rancher/issues/46642 (xs)

**Comment by richard-cox** [comment]
Linking request for index fields https://github.com/rancher/rancher/issues/46642

**Comment by moio** [comment]
Enablement by default did not happen in 2.10.

Splitting this issue to another targeting 2.11.

**Comment by moio** [comment]
iteration 3 appears here https://github.com/rancher/rancher/issues/48042
