### ISSUE TITLE
Merge tasks for 1.0.2

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4722]
* [x] remove bin/log #4584 
* [x] fix infinite loop for GMS rancher/cattle#1647
* [x] increasing number of agentRemovedExceptions #4682 
* [x] AWS+ELB w/ SSL termination+ HA #4697 
* [x] Add FORWARD iptable rule for Centos/RHEL that have a default REJECT rule #4323
* [x] Fix UI issue related to wrong hosts appearing in environments #4637
