### ISSUE TITLE
[EPIC] Wrangler V4

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#47333]
# Context

During the NA meetup we have discussed about wrangler and a few things we'd like to do to improve it. Even if wrangler is only used in Rancher core and k3s (now favoring controller-runtime for external controllers), we should try to fix its pain points.

# Tasks list

**Note:** This list may change over time, there were a few points brought during the meeting and some that we didn't have time to cover.

- [ ] https://github.com/rancher/rancher/issues/50585: Start with this so that everyone's aware of wrangler v4 being incompatible with v3. This will be painful once and then we'll avoid making breaking changes (when possible 🤞)
- [ ] https://github.com/rancher/rancher/issues/50586
- [ ] https://github.com/rancher/rancher/issues/50588

# Other ideas

This section is a list of ideas we've discussed at some point but we haven't created a task for it yet. I'm keeping it here since it was in this issue's description before the NA meetup. Note, the ideas below aren't to be worked on (and if they are, they'll be converted to a task and moved above).

**More flexible handler options**

The current interface looks like this and there is no way to extend it without [breaking compatibility](https://go.dev/blog/module-compatibility).

```go
type ControllerInterface[T RuntimeMetaObject, TList runtime.Object] interface {
	OnChange(ctx context.Context, name string, sync ObjectHandler[T])
	OnRemove(ctx context.Context, name string, sync ObjectHandler[T])
	...
}
```
We could add a `... OnRemoveOption` and `...OnChangeOption` parameter to change the behavior of handlers.
Here's an example PR that wanted this: https://github.com/rancher/wrangler/pull/472/.

**List from Jake during the meetup (that weren't ported to an issue yet)**

- Debugging/validation mechanisms for when invalid objects "pollute" cache
- Lack of deepcopy -> debug mode where we deepcopy & compare
- Improve support for watching/listing based on labels & field selectors
-Introduce feature for predicates/event filtering akin to kubebuilder
-Unify logging
- Address finalizers for removed controllers/controllers behind feature flags
- Relatedresource pitfalls (event filtering)
- Better handling regarding missing CRDs
- Sharding?

**Comment by aruiz14** [comment]
Still valid

**Comment by aruiz14** [comment]
Still valid

**Comment by tomleb** [comment]
Still valid

**Comment by aruiz14** [comment]
Still valid

**Comment by aruiz14** [comment]
Still valid
