### ISSUE TITLE
[EPIC] SQLite backed cache in the Steve API - iteration 3

### ISSUE THREAD

**Issue by moio** [rancher/rancher#48042]
**Blockers** for 2.11.0:

Frameworks Team to implement:
- [x] https://github.com/rancher/rancher/issues/46333 (UI P0)
- [x] https://github.com/rancher/rancher/issues/46410 (small things)
- [x] https://github.com/rancher/rancher/issues/46768 (UI P0)
- [x] https://github.com/rancher/rancher/issues/48473 (xs)
- [x] https://github.com/rancher/rancher/issues/48603 (UI P0)
- [x] https://github.com/rancher/rancher/issues/49288
- [x] https://github.com/rancher/rancher/issues/48092 (UI P0)
- [x] https://github.com/rancher/rancher/issues/48965

Bullseye Team to implement:
- [x] https://github.com/rancher/rancher/issues/48011 (xs)
- [x] https://github.com/rancher/rancher/issues/48103 (xs)
- [x] https://github.com/rancher/rancher/issues/48256 (xs)
- [x] https://github.com/rancher/rancher/issues/47825 (small things)
- [x] https://github.com/rancher/rancher/issues/48479
  - fixed by https://github.com/rancher/rancher/issues/48473 
- [x] https://github.com/rancher/rancher/issues/48384
  - fixed by https://github.com/rancher/rancher/issues/48256 

Hostbusters Team to implement:
- [x] https://github.com/rancher/rancher/issues/48509 (UI P0)

**Non-blockers**:

Frameworks Team to consider:

**Comment by gaktive** [comment]
@richard-cox should we add unclosed tickets like https://github.com/rancher/rancher/issues/46768 & https://github.com/rancher/rancher/issues/46333 to the next epic: https://github.com/rancher/rancher/issues/49250? 

QA is asking since they're in the midst of testing what's in 2.11.0 and are considering pushing this out to 2.12.0 as a result. I'll scan for other tickets here but I'll mention them in the newer epic.

**Comment by brudnak** [comment]
Reopened due to https://github.com/rancher/rancher/issues/49415

**Comment by richard-cox** [comment]
@gaktive  All of the issues have code merged to 2.11.0 (a few some time ago). Is the request to revert?

**Comment by gaktive** [comment]
@richard-cox nope, @rancher-max was asking more to see the state of this and if it needs to move to 2.12.0.
