### ISSUE TITLE
Document supported list of kubernetes 1.3 features

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5416]
#### API - V1

- [x] Secrets
- [x] Namespaces
- [x] Rolling updates
- [x] Configmaps
- [x] ResourceQuouta
- [x] Volume emptyDir
- [ ] Volume gitrepo #4976
- [x] PV HostPath
- [ ] PV GlusterFS #4348 
- [x] PV NFS 
- [ ] PV EBS #5591

#### API - V1beta

- [x] Deployments
- [x] DeploymentRollback
- [x] Jobs
- [x] scale
- [x] Daemonsets
- [x] replicasets
- [x] ingress

#### Addons

- [x] Dashboard 
- [ ] Heapster #5594
- [ ] Deis #5595

#### Kubectl

- [x] kubectl logs
- [x] kubectl exec

##### Pods:
- [x] Create pod
- [x] Create privileged pod  
- [x] Delete pod
- [x] Edit pod

- podspecs:
- [x] volumes
- [x] containers
- [x] restartPolicy
- [x] terminationGracePeriodSeconds
- [x] activeDeadlineSeconds
- [x] nodeSelector
- [x] nodeName
- [x] hostNetwork 
- [x] hostPID
- [x] hostIPC 
- [x] securityContext
- [x] imagePullSecret
- [x] serviceAccountName 

##### Replication Controllers
- [x] create rc
- [x] Delete rc
- [x] Cascade delete rc  
- [ ] Isolating pods from rc #4356 
- [x] Scale RC

- ReplicationControllersSpec
- [x] replicas
- [x] selector
- [x] template

#### Services
- [x] Create services
- [x] Delete services
- [x] Editing services

- servicespec
- [x] ports
- [x] selector
- [x] clusterIP
- [x] type
- [ ] loadBalancerIP - can't be specified for Rancher load balancer
- [x] sessionAffinity
- [x] externalIPs

- [x] stateful apps (petSet) https://github.com/rancher/rancher/issues/5236
- [ ] federated clusters (Ubernetes) https://github.com/rancher/rancher/issues/5237

**Comment by alena1108** [comment]
@galal-hussein we should start evaluating k8s 1.3 features once it is published to rancher-catalog. I've listed 2 major ones, please go over the rest to see if there is anything requiring fixes in Rancher kubernetes (similar to https://github.com/rancher/rancher/issues/4489).

**Comment by galal-hussein** [comment]
@alena1108 Sure, I will start evaluating k8s 1.3 once its released in the rancher-catalog.

**Comment by alena1108** [comment]
@galal-hussein you can start evaluation assuming all our regular tests passed against 1.3

please chat with @wlan0 regarding pet set support testing
