### ISSUE TITLE
Issues related to turning off or switching types of authentication

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5450]
**Rancher Version:** Master 7/15

**Steps to Reproduce:**
- [ ] Switching from Open LDAP to Local, login box still has open ldap info
  ![image](https://cloud.githubusercontent.com/assets/11514927/16890673/9406f204-4aa5-11e6-837b-1f6e92f4bb9c.png)
- [ ] Environment drop-down and permissions are messed up after switching Auth off and/or switching authentication types (including from Github to Enterprise) #959 
- [ ] Switching between authentication type shows all accounts regardless of authentication type #2013 
- [ ] Name is not being removed if I reauth in local auth #4038 
- [ ] Full Name is not being overwritten if Login name already exist #4508

**Expected:**  All these issues should be considered when taking turning off or switching authentication into account

**Comment by westlywright** [comment]
@tfiduccia can we retest this? I ran through what I thought the steps were to repro this in the current build and didn't see any the issues.

**Comment by tfiduccia** [comment]
These issue still exist.  But I think they won't really be fixed until we implement the multiple auth scenarios.

**Comment by deniseschannon** [comment]
As Auth is completely re-written, we'll wait until new auth providers are added into the new framework and close for now.
