### ISSUE TITLE
Aliyun features support in Cattle

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9177]
- [x] Webhooks support for Aliyun docker hub https://github.com/rancher/rancher/issues/9175
- [x] SLB support https://github.com/rancher/rancher/issues/8921
- [x] NAS support(same with NFS, but need test)
- [x] Block Storage support https://github.com/rancher/rancher/issues/9194
- [x] Agent cloud provider for Aliyun https://github.com/rancher/rancher/issues/9318
- [x] Support Aliyun DNS in Rancher external-dns https://github.com/rancher/rancher/issues/9382
- [ ] Aliyun Cloud Provider for Rancher Kubernetes
- [ ] Support Aliyun VPC for per-host-subnet networking https://github.com/rancher/rancher/issues/9990

**Comment by yasker** [comment]
#9382 merged.
