### ISSUE TITLE
POWER8 Rancher environments (WIP)

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#9751]
The goal of this is to collect all PRs required for enabling Rancher environments composed of `ppc64le` (IBM POWER8) hosts, and an x86_64 Rancher server.

The current targeted version is **`rancher/server:v1.6.7`** (`rancher/agent:v1.2.5`).

### Base

*   [ ] Multi-arch Dapper [[rancher/dapper#44](https://github.com/rancher/dapper/pull/44)]

### Rancher Server

*   [ ] cattle

### Rancher Agent

*   [ ] [[rancher/share-mnt#1](https://github.com/rancher/share-mnt/pull/1)]
*   [ ] [[rancher/weave#1](https://github.com/rancher/weave/pull/1)]
*   [ ] rancher/agent
*   [ ] rancher/rancher (agent-base, agent)

### Infrastructure Services

*   [ ] network-policy-manager ([WIP](https://github.com/zambon/rancher__network-policy-manager))

*   [ ] network-services

    *   [ ] plugin-manager ([WIP](https://github.com/zambon/rancher__plugin-manager/tree/v0.7.7-multi-dapper))
    *   [ ] rancher-metadata ([WIP](https://github.com/zambon/rancher__rancher-metadata/tree/v0.9.3-multi-dapper))
    *   [ ] rancher-dns ([WIP](https://github.com/zambon/rancher__rancher-dns/tree/v0.15.1-multi-dapper))

*   [ ] ipsec

    *   [ ] rancher-net ([WIP](https://github.com/zambon/rancher__rancher-net/tree/v0.11.7-multi))

        *   [ ] [[rancher/strongswan-package#6](https://github.com/rancher/strongswan-package/pull/6)]
        *   [ ] [[rancher/cni#7](https://github.com/rancher/cni/pull/7)]
        *   [ ] rancher-cni-ipam ([WIP](https://github.com/zambon/rancher__rancher-cni-ipam/tree/v0.1.1-multi))
        *   [ ] rancher-cni-bridge ([WIP](https://github.com/zambon/rancher__rancher-cni-bridge/tree/v0.5.0-multi))

*   [ ] scheduler ([WIP](https://github.com/zambon/rancher__scheduler/tree/v0.8.2-multi))

*   [ ] healthcheck ([WIP](https://github.com/zambon/rancher__healthcheck/tree/v0.3.1-multi))

    *   [ ] Multi-arch Tini (v0.15.0) [[krallin/tini#98](https://github.com/krallin/tini/pull/98)]

**Comment by ibuildthecloud** [comment]
@zambon Is there still interest in getting this merged in?  I was looking over a bunch of it.  I had a question about `zambon/ubuntu-multi:16.04` which is used a lot.  Is that image required?  Can we use the standard `ubuntu:16.04`?
